import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styles from '../styles/style.css'
import CoinGecko from 'coingecko-api';
const coinGeckoClient = new CoinGecko();

export default function Home(props) {
  const { data } = props.result;

  const formatPercent = number =>
    `${new Number(number).toFixed(2)}%`

  const formatDollar = (number, maximumSignificantDigits) =>
    new Intl.NumberFormat(
      'en-US',
      {
        style: 'currency',
        currency: 'usd',
        maximumSignificantDigits
      })
      .format(number);

  //  console.log(props.results);
  return (
    <div className={styles.container}>
      <Head>
        <title>ICMARKETCAP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2366281900785792" crossorigin="anonymous"></script>
      </Head>
      
      <header>
        <h1>IC MarketCap</h1>
        <h1 class="logo">Logo</h1>
        <input type="checkbox" id="nav-toggle" class="nav-toggle">
        <nav>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </nav>
        <label for="nav-toggle" class="nav-toggle-label">
            <span></span>
        </label>
    </header>

      <table className='table'>
           <tr>
          <th>Symbol</th>
          <th>24H Change</th>
          <th>Price</th>
          <th>Market cap</th>
        </tr>
        <tbody>
          {data.map(coin => (
            <tr key={coin.id}>
              <td>
                <img
                  src={coin.image}
                  style={{ width: 25, height: 25, marginRight: 10 }}
                />

                {coin.symbol.toUpperCase()}
              </td>

              <td>
                <span
                  className={coin.price_change_percentage_24h > 0 ? (
                    'text-success'
                  ) : 'text-danger'}
                >
                  {formatPercent(coin.price_change_percentage_24h)}
                </span>

              </td>
              <td>{formatDollar(coin.current_price, 20)}</td>
              <td>{formatDollar(coin.market_cap, 12)}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

export async function getServerSideProps(context) {
  const params = {
    order: CoinGecko.ORDER.MARKET_CAP_DESC
  }
  const result = await coinGeckoClient.coins.markets({ params });
  return {
    props: {
      result
    }
  };
}
